/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StopWatch {
    'applyHover': boolean;
    'hours': string;
    'milliseconds': string;
    'minutes': string;
    'seconds': string;
  }
  interface StopWatchBox {
    'applyHover': boolean;
  }
}

declare global {


  interface HTMLStopWatchElement extends Components.StopWatch, HTMLStencilElement {}
  var HTMLStopWatchElement: {
    prototype: HTMLStopWatchElement;
    new (): HTMLStopWatchElement;
  };

  interface HTMLStopWatchBoxElement extends Components.StopWatchBox, HTMLStencilElement {}
  var HTMLStopWatchBoxElement: {
    prototype: HTMLStopWatchBoxElement;
    new (): HTMLStopWatchBoxElement;
  };
  interface HTMLElementTagNameMap {
    'stop-watch': HTMLStopWatchElement;
    'stop-watch-box': HTMLStopWatchBoxElement;
  }
}

declare namespace LocalJSX {
  interface StopWatch extends JSXBase.HTMLAttributes<HTMLStopWatchElement> {
    'applyHover'?: boolean;
    'hours'?: string;
    'milliseconds'?: string;
    'minutes'?: string;
    'seconds'?: string;
  }
  interface StopWatchBox extends JSXBase.HTMLAttributes<HTMLStopWatchBoxElement> {
    'applyHover'?: boolean;
  }

  interface IntrinsicElements {
    'stop-watch': StopWatch;
    'stop-watch-box': StopWatchBox;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


